### PR TITLE
Extend client side with RSA key operation support

### PR DESCRIPTION
**Pull request by stefanberger**
Add support for RSA keys and operations with RSA keys, such
as signing and decryption. The Sign() operation support also
pulls in some aspects of hashing.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

### CODE REVIEW

**Comment by stefanberger** [comment]
I ran `gofmt` over consts.go, so that's why there are so many changes.

**Comment by stefanberger** [comment]
Had been wrong version of go (1.10) that formatted the source differently...

**Comment by stefanberger** [comment]
@smira Comments?

**Review by smira — APPROVED** [review]
Stefan, sorry for late response - got back from holidays. This looks great to me! :+1:

**Comment by smira** [comment]
I also thought of adding some simple integration tests against "mock" KMIP service, to excercise more code paths in the tests.

**Comment by stefanberger** [comment]
Yes, testing is a bigger problem. If there was a (free) server product out there one could install that would make client development and testing a lot easier.

**Pull request merged**
